config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :tracking_times
  resources :tasks do
    collection do
      post :command
    end
  end
  resources :categories
  resources :brands
  # resources :users
  resources :momo do
    collection do
      get :send_to_momo
      get :send_to_vnpay
    end
  end
  get 'momo/ipn'
  post 'momo/ipn'
  get 'momo/return_url'
  post 'momo/return_url'
  get 'momo/handle_ipn' => "momo#handle_ipn"
  post 'momo/handle_ipn' => "momo#handle_ipn"
end

app/models/tracking_time.rb
class TrackingTime < ApplicationRecord
  belongs_to :task

  enum status: %w[starting finished]
  scope :track_today, ->() {where('date(tracking_times.start_at) = CURRENT_DATE OR date(tracking_times.end_at) = CURRENT_DATE')}

end

app/controllers/tracking_times_controller.rb
class TrackingTimesController < ApplicationController
  before_action :set_tracking_time, only: [:show, :edit, :update, :destroy]

  # GET /tracking_times
  # GET /tracking_times.json
  def index
    @tracking_times = TrackingTime.all
  end

  # GET /tracking_times/1
  # GET /tracking_times/1.json
  def show
  end

  # GET /tracking_times/new
  def new
    @tracking_time = TrackingTime.new
  end

  # GET /tracking_times/1/edit
  def edit
  end

  # POST /tracking_times
  # POST /tracking_times.json
  def create
    @tracking_time = TrackingTime.new(tracking_time_params)

    respond_to do |format|
      if @tracking_time.save
        format.html { redirect_to @tracking_time, notice: 'Tracking time was successfully created.' }
        format.json { render :show, status: :created, location: @tracking_time }
      else
        format.html { render :new }
        format.json { render json: @tracking_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracking_times/1
  # PATCH/PUT /tracking_times/1.json
  def update
    respond_to do |format|
      if @tracking_time.update(tracking_time_params)
        format.html { redirect_to @tracking_time, notice: 'Tracking time was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracking_time }
      else
        format.html { render :edit }
        format.json { render json: @tracking_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracking_times/1
  # DELETE /tracking_times/1.json
  def destroy
    @tracking_time.destroy
    respond_to do |format|
      format.html { redirect_to tracking_times_url, notice: 'Tracking time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracking_time
      @tracking_time = TrackingTime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracking_time_params
      params.require(:tracking_time).permit(:task_id, :start_at, :end_at)
    end
end

app/helpers/tracking_times_helper.rb
module TrackingTimesHelper
end

app/views/tracking_times/_form.html.erb
<%= form_with(model: tracking_time, local: true) do |form| %>
  <% if tracking_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracking_time.errors.count, "error") %> prohibited this tracking_time from being saved:</h2>

      <ul>
        <% tracking_time.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.text_field :start_at %>
  </div>

  <div class="field">
    <%= form.label :end_at %>
    <%= form.text_field :end_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracking_times/_inline.html.erb
<%
  task_checked = false
  if record.end_at.present?
    if record.task.last_tracking_id == record.id
      class_border = 'border-green'
      task_checked = true if record.task.status == 'done'
    else
      class_border = 'border-stall-dim'
    end
  else
    class_border = 'border-orange'
  end
%>
<div class="mb-2 d-flex flex-row track-time-item" id="track-time-<%= record.id %>" data-task-id="<%= record.task.serial %>">
  <div class="text-right text-sm pr-3 mr-3 border-r-2 <%= class_border %>">
    <span class="block text-stall-dim"><%= record.start_at&.strftime("%I:%M:%S %p") %></span>
    <br>
    <span class="block"><%= record.end_at&.strftime("%I:%M:%S %p") %></span>
  </div>
  <div class="flex-1">
    <div>
      <% if record.task.status == 'in_progress' %>
        <span class="text-warning text-large">*</span>
      <% end %>
      <%= record.task.description.html_safe %>
    </div>
    <div class="text-small text-stall-dim">
      <span class="total-time">
        <% if task_checked %>
          <span class="text-success">✔</span>
        <% end %>
        <% if record.start_at.present? && record.end_at.present? %>
          <%= hms(record.end_at - record.start_at) %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/tracking_times/edit.html.erb
<h1>Editing Tracking Time</h1>

<%= render 'form', tracking_time: @tracking_time %>

<%= link_to 'Show', @tracking_time %> |
<%= link_to 'Back', tracking_times_path %>

app/views/tracking_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracking Times</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Start at</th>
      <th>End at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracking_times.each do |tracking_time| %>
      <tr>
        <td><%= tracking_time.task_id %></td>
        <td><%= tracking_time.start_at %></td>
        <td><%= tracking_time.end_at %></td>
        <td><%= link_to 'Show', tracking_time %></td>
        <td><%= link_to 'Edit', edit_tracking_time_path(tracking_time) %></td>
        <td><%= link_to 'Destroy', tracking_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracking Time', new_tracking_time_path %>

app/views/tracking_times/new.html.erb
<h1>New Tracking Time</h1>

<%= render 'form', tracking_time: @tracking_time %>

<%= link_to 'Back', tracking_times_path %>

app/views/tracking_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @tracking_time.task_id %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @tracking_time.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @tracking_time.end_at %>
</p>

<%= link_to 'Edit', edit_tracking_time_path(@tracking_time) %> |
<%= link_to 'Back', tracking_times_path %>